#!/usr/bin/env perl

use warnings;
use strict;
use Daemon::Control;

use ENV::Util -load_dotenv;

use Cwd qw(abs_path);
use File::Basename;

my $abs_path = abs_path($0);
my $abs_dir  = dirname($0);

my @vars = qw[HOST NAME USER PASS];

if (grep { ! $ENV{"PASTE_DB_$_"} } @vars) {
  die "Please define the DB connection variables: PASTE_DB*\n";
}

my @program_args;

if ($ENV{PASTE_WORKER_COUNT}) {
  push @program_args, '--workers', $ENV{PASTE_WORKER_COUNT};
}
if ($ENV{PASTE_APP_PORT}) {
  push @program_args, '-l', ":$ENV{PASTE_APP_PORT}";
}
if ($ENV{PASTE_APP_PRELOAD}) {
  push @program_args, '--preload-app';
}
push @program_args, "$abs_dir/bin/app.psgi";

Daemon::Control->new({
  name      => ucfirst lc $ENV{PASTE_APP_NAME},
  lsb_start => '$syslog $remote_fs',
  lsb_stop  => '$syslog',
  lsb_sdesc => 'AdServer',
  lsb_desc  => 'AdServer',
  path      => $abs_path,

  program      => '/usr/bin/starman',
  program_args => \@program_args,

  user  => $ENV{PASTE_OWNER},
  group => $ENV{PASTE_GROUP},

  pid_file    => "/var/run/$ENV{PASTE_APP_NAME}.pid",
  stderr_file => "$ENV{PASTE_LOG_DIR}/error.log",
  stdout_file => "$ENV{PASTE_LOG_DIR}/output.log",

  fork => 2,
})->run;
